### ISSUE TITLE
openmeetup/meetupedia website is down

### ISSUE THREAD

**Issue by heyakyra** [meetupedia/OpenMeetup#86]
Ruby on Rails application could not be started
These are the possible causes:

```
There may be a syntax error in the application's code. Please check for such errors and fix them.
A required library may not installed. Please install all libraries that this application requires.
The application may not be properly configured. Please check whether all configuration files are written correctly, fix any incorrect configurations, and restart this application.
A service that the application relies on (such as the database server or the Ferret search engine server) may not have been started. Please start that service.
```

Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.

Error message:
    /var/www/openmeetup/app/mailers/post_mailer.rb:14: class definition in method body /var/www/openmeetup/app/mailers/post_mailer.rb:23: syntax error, unexpected $end, expecting keyword_end
Exception class:
    SyntaxError
Application root:
    /var/www/openmeetup 
Backtrace:
    #   File    Line    Location
    0   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     251     in `require'
    1   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     251     in`block in require'
    2   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     236     in `load_dependency'
    3   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     251     in`require'
    4   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     359     in `require_or_load'
    5   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     313     in`depend_on'
    6   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.11/lib/active_support/dependencies.rb     225     in `require_dependency'
    7   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/engine.rb     439     in`block (2 levels) in eager_load!'
    8   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/engine.rb     438     in `each'
    9   /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/engine.rb     438     in`block in eager_load!'
    10  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/engine.rb     436     in `each'
    11  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/engine.rb     436     in`eager_load!'
    12  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/application/finisher.rb   53  in `block in '
    13  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/initializable.rb  30  in`instance_exec'
    14  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/initializable.rb  30  in `run'
    15  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/initializable.rb  55  in`block in run_initializers'
    16  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/initializable.rb  54  in `each'
    17  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/initializable.rb  54  in`run_initializers'
    18  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/application.rb    136     in `initialize!'
    19  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.11/lib/rails/railtie/configurable.rb   30  in`method_missing'
    20  /var/www/openmeetup/config/environment.rb   5   in `'
    21  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb     222     in`require'
    22  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb     222     in `preload_application'
    23  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb     181     in`block in initialize_server'
    24  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/utils.rb     563     in `report_app_init_status'
    25  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb     174     in`initialize_server'
    26  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb   204     in `start_synchronously'
    27  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb   180     in`start'
    28  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb     149     in `start'
    29  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb     219     in`block (2 levels) in spawn_rails_application'
    30  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb    132     in `lookup_or_add'
    31  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb     214     in`block in spawn_rails_application'
    32  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb    82  in `block in synchronize'
    33      prelude>    10:in`synchronize'
    34  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb    79  in `synchronize'
    35  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb     213     in`spawn_rails_application'
    36  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb     132     in `spawn_application'
    37  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb     275     in`handle_spawn_application'
    38  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb   357     in `server_main_loop'
    39  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb   206     in`start_synchronously'
    40  /home/meetupedia/.rvm/gems/ruby-1.9.3-p374/gems/passenger-3.0.19/helper-scripts/passenger-spawn-server  99  in `'

**Comment by frkandris** [comment]
thank you, i've fixed it.
